// AI 工具数据库 - 100+ 工具

export interface AITool {
  id: string
  name: string
  url: string
  description: string
  category: string
  tags: string[]
  pricing: string
  rating: number
  popularity: number
  chinese: boolean
  icon: string
  color: string
}

export const aiToolsDatabase: AITool[] = [
  // ============== 对话助手 (12 个) ==============
  {
    id: '1',
    name: 'ChatGPT',
    url: 'https://chat.openai.com',
    description: 'OpenAI 开发的大型语言模型，支持对话、写作、编程、分析等多种任务',
    category: '对话助手',
    tags: ['聊天机器人', '写作', '编程', '通用 AI'],
    pricing: '免费 + 付费',
    rating: 4.9,
    popularity: 100000,
    chinese: false,
    icon: '🤖',
    color: 'green'
  },
  {
    id: '2',
    name: 'Claude',
    url: 'https://claude.ai',
    description: 'Anthropic 开发的 AI 助手，擅长长文本理解、分析和写作',
    category: '对话助手',
    tags: ['聊天机器人', '文档分析', '写作'],
    pricing: '免费',
    rating: 4.8,
    popularity: 80000,
    chinese: false,
    icon: '🧠',
    color: 'orange'
  },
  {
    id: '3',
    name: '通义千问',
    url: 'https://tongyi.aliyun.com',
    description: '阿里云开发的超大规模语言模型，支持多轮对话、内容创作、代码生成',
    category: '对话助手',
    tags: ['聊天机器人', '国产', '多模态'],
    pricing: '免费',
    rating: 4.7,
    popularity: 90000,
    chinese: true,
    icon: '🤖',
    color: 'purple'
  },
  {
    id: '4',
    name: '文心一言',
    url: 'https://yiyan.baidu.com',
    description: '百度开发的知识增强大语言模型，支持对话、创作、逻辑推理',
    category: '对话助手',
    tags: ['聊天机器人', '国产', '知识增强'],
    pricing: '免费',
    rating: 4.5,
    popularity: 75000,
    chinese: true,
    icon: '💬',
    color: 'blue'
  },
  {
    id: '5',
    name: 'Kimi 智能助手',
    url: 'https://kimi.moonshot.cn',
    description: '月之暗面开发的智能助手，擅长长文本理解和多轮对话',
    category: '对话助手',
    tags: ['聊天机器人', '国产', '长文本'],
    pricing: '免费',
    rating: 4.6,
    popularity: 60000,
    chinese: true,
    icon: '🌙',
    color: 'indigo'
  },
  {
    id: '6',
    name: '智谱清言',
    url: 'https://chatglm.cn',
    description: '智谱 AI 开发的大模型对话助手，支持多轮对话和内容创作',
    category: '对话助手',
    tags: ['聊天机器人', '国产', '清华系'],
    pricing: '免费',
    rating: 4.5,
    popularity: 50000,
    chinese: true,
    icon: '💭',
    color: 'cyan'
  },
  {
    id: '7',
    name: '讯飞星火',
    url: 'https://xinghuo.xfyun.cn',
    description: '科大讯飞推出的大语言模型，支持多轮对话和知识问答',
    category: '对话助手',
    tags: ['聊天机器人', '国产', '语音'],
    pricing: '免费',
    rating: 4.4,
    popularity: 45000,
    chinese: true,
    icon: '⭐',
    color: 'blue'
  },
  {
    id: '8',
    name: '360 智脑',
    url: 'https://brain.360.cn',
    description: '360 公司推出的大语言模型，支持对话和创作',
    category: '对话助手',
    tags: ['聊天机器人', '国产', '安全'],
    pricing: '免费',
    rating: 4.2,
    popularity: 30000,
    chinese: true,
    icon: '🔮',
    color: 'green'
  },
  {
    id: '9',
    name: '腾讯混元',
    url: 'https://hunyuan.tencent.com',
    description: '腾讯推出的全链路大模型，支持多模态任务',
    category: '对话助手',
    tags: ['聊天机器人', '国产', '多模态'],
    pricing: '免费',
    rating: 4.3,
    popularity: 40000,
    chinese: true,
    icon: '🌐',
    color: 'blue'
  },
  {
    id: '10',
    name: 'MiniMax',
    url: 'https://api.minimax.chat',
    description: '国内 AI 公司的大模型，擅长对话和内容生成',
    category: '对话助手',
    tags: ['聊天机器人', '国产', 'API'],
    pricing: '免费 + 付费',
    rating: 4.4,
    popularity: 25000,
    chinese: true,
    icon: '💫',
    color: 'purple'
  },
  {
    id: '11',
    name: 'Character.ai',
    url: 'https://character.ai',
    description: '创建和对话虚拟角色的 AI 平台',
    category: '对话助手',
    tags: ['角色扮演', '虚拟角色', '娱乐'],
    pricing: '免费 + 付费',
    rating: 4.6,
    popularity: 70000,
    chinese: false,
    icon: '🎭',
    color: 'pink'
  },
  {
    id: '12',
    name: 'Pi',
    url: 'https://pi.ai',
    description: 'Inflection AI 开发的个人 AI 助手，注重情感交流',
    category: '对话助手',
    tags: ['个人助手', '情感交流', '陪伴'],
    pricing: '免费',
    rating: 4.5,
    popularity: 35000,
    chinese: false,
    icon: '🥧',
    color: 'orange'
  },

  // ============== AI 写作 (10 个) ==============
  {
    id: '101',
    name: 'Jasper',
    url: 'https://www.jasper.ai',
    description: 'AI 内容创作平台，专为营销人员设计，支持博客、广告、社交媒体内容',
    category: 'AI 写作',
    tags: ['营销文案', '博客写作', '社交媒体'],
    pricing: '付费',
    rating: 4.4,
    popularity: 45000,
    chinese: false,
    icon: '✍️',
    color: 'pink'
  },
  {
    id: '102',
    name: 'Notion AI',
    url: 'https://www.notion.so/product/ai',
    description: 'Notion 内置的 AI 助手，帮助写作、总结、翻译、头脑风暴',
    category: 'AI 写作',
    tags: ['笔记', '写作辅助', ' productivity'],
    pricing: '付费',
    rating: 4.6,
    popularity: 70000,
    chinese: true,
    icon: '📝',
    color: 'gray'
  },
  {
    id: '103',
    name: '秘塔写作猫',
    url: 'https://xiezuocat.com',
    description: '国产 AI 写作助手，支持文章生成、润色、纠错、翻译',
    category: 'AI 写作',
    tags: ['写作辅助', '国产', '纠错'],
    pricing: '免费 + 付费',
    rating: 4.3,
    popularity: 35000,
    chinese: true,
    icon: '🐱',
    color: 'orange'
  },
  {
    id: '104',
    name: 'Grammarly',
    url: 'https://www.grammarly.com',
    description: 'AI 驱动的写作助手，检查语法、拼写、标点，提供写作建议',
    category: 'AI 写作',
    tags: ['语法检查', '英语写作', '纠错'],
    pricing: '免费 + 付费',
    rating: 4.7,
    popularity: 85000,
    chinese: false,
    icon: '✅',
    color: 'green'
  },
  {
    id: '105',
    name: 'Copy.ai',
    url: 'https://www.copy.ai',
    description: 'AI 文案生成工具，快速创建营销文案、产品描述、广告语',
    category: 'AI 写作',
    tags: ['营销文案', '产品描述', '广告'],
    pricing: '免费 + 付费',
    rating: 4.3,
    popularity: 40000,
    chinese: false,
    icon: '📋',
    color: 'blue'
  },
  {
    id: '106',
    name: 'Writesonic',
    url: 'https://writesonic.com',
    description: 'AI 写作平台，支持博客、广告、产品描述等多种内容',
    category: 'AI 写作',
    tags: ['内容创作', '营销', 'SEO'],
    pricing: '免费 + 付费',
    rating: 4.2,
    popularity: 30000,
    chinese: false,
    icon: '✒️',
    color: 'purple'
  },
  {
    id: '107',
    name: 'Rytr',
    url: 'https://rytr.me',
    description: '经济实惠的 AI 写作助手，支持 30+ 语言和 20+ 用例',
    category: 'AI 写作',
    tags: ['写作助手', '多语言', '实惠'],
    pricing: '免费 + 付费',
    rating: 4.1,
    popularity: 25000,
    chinese: false,
    icon: '🖊️',
    color: 'blue'
  },
  {
    id: '108',
    name: '火山写作',
    url: 'https://writing.volcengine.com',
    description: '字节跳动推出的 AI 写作平台，支持多种文体',
    category: 'AI 写作',
    tags: ['写作', '国产', '字节'],
    pricing: '免费',
    rating: 4.3,
    popularity: 28000,
    chinese: true,
    icon: '🌋',
    color: 'red'
  },
  {
    id: '109',
    name: 'Effie',
    url: 'https://www.effie.co',
    description: 'AI 驱动的写作软件，支持大纲、思维导图、混排',
    category: 'AI 写作',
    tags: ['写作软件', '大纲', '思维导图'],
    pricing: '付费',
    rating: 4.4,
    popularity: 20000,
    chinese: true,
    icon: '📖',
    color: 'yellow'
  },
  {
    id: '110',
    name: '笔神',
    url: 'https://www.bishen.ink',
    description: '国产 AI 写作助手，提供写作素材和灵感',
    category: 'AI 写作',
    tags: ['写作辅助', '国产', '素材'],
    pricing: '免费 + 付费',
    rating: 4.0,
    popularity: 15000,
    chinese: true,
    icon: '🖋️',
    color: 'green'
  },

  // ============== AI 绘画 (12 个) ==============
  {
    id: '201',
    name: 'Midjourney',
    url: 'https://www.midjourney.com',
    description: '最流行的 AI 艺术生成工具，通过文字描述创建精美图像',
    category: 'AI 绘画',
    tags: ['图像生成', '艺术创作', 'Discord'],
    pricing: '付费',
    rating: 4.8,
    popularity: 95000,
    chinese: false,
    icon: '🎨',
    color: 'purple'
  },
  {
    id: '202',
    name: 'Stable Diffusion',
    url: 'https://stability.ai',
    description: '开源的 AI 图像生成模型，可本地部署，高度可定制',
    category: 'AI 绘画',
    tags: ['图像生成', '开源', '本地部署'],
    pricing: '免费',
    rating: 4.6,
    popularity: 80000,
    chinese: false,
    icon: '🌊',
    color: 'blue'
  },
  {
    id: '203',
    name: 'DALL-E 3',
    url: 'https://openai.com/dall-e-3',
    description: 'OpenAI 开发的图像生成模型，理解能力强，生成质量高',
    category: 'AI 绘画',
    tags: ['图像生成', 'OpenAI', '高质量'],
    pricing: '付费',
    rating: 4.7,
    popularity: 75000,
    chinese: false,
    icon: '🖼️',
    color: 'green'
  },
  {
    id: '204',
    name: '文心一格',
    url: 'https://yige.baidu.com',
    description: '百度推出的 AI 艺术创作平台，支持多种艺术风格',
    category: 'AI 绘画',
    tags: ['图像生成', '国产', '艺术风格'],
    pricing: '免费 + 付费',
    rating: 4.4,
    popularity: 55000,
    chinese: true,
    icon: '🎭',
    color: 'purple'
  },
  {
    id: '205',
    name: '通义万相',
    url: 'https://wanxiang.aliyun.com',
    description: '阿里云推出的 AI 绘画工具，支持文生图、图生图',
    category: 'AI 绘画',
    tags: ['图像生成', '国产', '阿里系'],
    pricing: '免费',
    rating: 4.5,
    popularity: 50000,
    chinese: true,
    icon: '🖌️',
    color: 'blue'
  },
  {
    id: '206',
    name: 'Leonardo.ai',
    url: 'https://leonardo.ai',
    description: '专业的 AI 艺术生成平台，适合游戏美术、概念设计',
    category: 'AI 绘画',
    tags: ['游戏美术', '概念设计', '专业'],
    pricing: '免费 + 付费',
    rating: 4.6,
    popularity: 45000,
    chinese: false,
    icon: '🦁',
    color: 'yellow'
  },
  {
    id: '207',
    name: 'DreamStudio',
    url: 'https://dreamstudio.ai',
    description: 'Stability AI 官方的图像生成平台',
    category: 'AI 绘画',
    tags: ['图像生成', 'Stability AI', '官方'],
    pricing: '免费 + 付费',
    rating: 4.4,
    popularity: 40000,
    chinese: false,
    icon: '🌈',
    color: 'purple'
  },
  {
    id: '208',
    name: 'LiblibAI',
    url: 'https://www.liblib.ai',
    description: '国内领先的 AI 创作平台，提供丰富模型',
    category: 'AI 绘画',
    tags: ['图像生成', '国产', '模型库'],
    pricing: '免费 + 付费',
    rating: 4.5,
    popularity: 48000,
    chinese: true,
    icon: '📚',
    color: 'blue'
  },
  {
    id: '209',
    name: 'Tiamat',
    url: 'https://www.tiamat.world',
    description: '国产 AI 艺术生成工具，风格独特',
    category: 'AI 绘画',
    tags: ['艺术生成', '国产', '独特风格'],
    pricing: '免费 + 付费',
    rating: 4.3,
    popularity: 25000,
    chinese: true,
    icon: '🐉',
    color: 'purple'
  },
  {
    id: '210',
    name: '美图 AI',
    url: 'https://xiuxiu.meitu.com/ai',
    description: '美图秀秀推出的 AI 绘画工具',
    category: 'AI 绘画',
    tags: ['图像生成', '国产', '美图'],
    pricing: '免费',
    rating: 4.2,
    popularity: 60000,
    chinese: true,
    icon: '📸',
    color: 'pink'
  },
  {
    id: '211',
    name: 'Civitai',
    url: 'https://civitai.com',
    description: 'Stable Diffusion 模型分享平台',
    category: 'AI 绘画',
    tags: ['模型分享', '社区', 'SD'],
    pricing: '免费',
    rating: 4.7,
    popularity: 70000,
    chinese: false,
    icon: '🏛️',
    color: 'purple'
  },
  {
    id: '212',
    name: 'SeaArt',
    url: 'https://www.seaart.ai',
    description: '一站式 AI 艺术创作平台',
    category: 'AI 绘画',
    tags: ['艺术创作', '一站式', '平台'],
    pricing: '免费 + 付费',
    rating: 4.3,
    popularity: 30000,
    chinese: false,
    icon: '🌊',
    color: 'blue'
  },

  // ============== AI 视频 (10 个) ==============
  {
    id: '301',
    name: 'Runway',
    url: 'https://runwayml.com',
    description: 'AI 视频编辑和生成工具，支持绿幕抠图、视频生成、风格转换',
    category: 'AI 视频',
    tags: ['视频编辑', '视频生成', '绿幕'],
    pricing: '免费 + 付费',
    rating: 4.5,
    popularity: 50000,
    chinese: false,
    icon: '🎬',
    color: 'purple'
  },
  {
    id: '302',
    name: 'Sora',
    url: 'https://openai.com/sora',
    description: 'OpenAI 开发的文生视频模型，可生成长达 1 分钟的高清视频',
    category: 'AI 视频',
    tags: ['视频生成', 'OpenAI', '文生视频'],
    pricing: '未开放',
    rating: 4.9,
    popularity: 100000,
    chinese: false,
    icon: '🎥',
    color: 'green'
  },
  {
    id: '303',
    name: '剪映',
    url: 'https://www.capcut.cn',
    description: '字节跳动推出的智能视频编辑工具，AI 功能丰富',
    category: 'AI 视频',
    tags: ['视频编辑', '国产', '字节'],
    pricing: '免费',
    rating: 4.6,
    popularity: 90000,
    chinese: true,
    icon: '✂️',
    color: 'black'
  },
  {
    id: '304',
    name: 'HeyGen',
    url: 'https://www.heygen.com',
    description: 'AI 数字人视频生成平台，创建虚拟主播和讲解视频',
    category: 'AI 视频',
    tags: ['数字人', '虚拟主播', '讲解视频'],
    pricing: '免费 + 付费',
    rating: 4.4,
    popularity: 40000,
    chinese: false,
    icon: '👤',
    color: 'blue'
  },
  {
    id: '305',
    name: 'Pika',
    url: 'https://pika.art',
    description: '新兴的 AI 视频生成工具，操作简单，效果好',
    category: 'AI 视频',
    tags: ['视频生成', '新兴', '简单'],
    pricing: '免费 + 付费',
    rating: 4.5,
    popularity: 45000,
    chinese: false,
    icon: '✨',
    color: 'pink'
  },
  {
    id: '306',
    name: 'Luma Dream Machine',
    url: 'https://lumalabs.ai/dream-machine',
    description: 'Luma AI 推出的视频生成模型',
    category: 'AI 视频',
    tags: ['视频生成', 'Luma', '高质量'],
    pricing: '免费 + 付费',
    rating: 4.6,
    popularity: 55000,
    chinese: false,
    icon: '💫',
    color: 'purple'
  },
  {
    id: '307',
    name: '可灵 AI',
    url: 'https://klingai.kuaishou.com',
    description: '快手推出的 AI 视频生成大模型',
    category: 'AI 视频',
    tags: ['视频生成', '国产', '快手'],
    pricing: '免费',
    rating: 4.5,
    popularity: 65000,
    chinese: true,
    icon: '🎞️',
    color: 'orange'
  },
  {
    id: '308',
    name: 'D-ID',
    url: 'https://www.d-id.com',
    description: 'AI 数字人视频平台，让照片说话',
    category: 'AI 视频',
    tags: ['数字人', '照片说话', '虚拟人'],
    pricing: '免费 + 付费',
    rating: 4.3,
    popularity: 35000,
    chinese: false,
    icon: '🗣️',
    color: 'blue'
  },
  {
    id: '309',
    name: 'Synthesia',
    url: 'https://www.synthesia.io',
    description: 'AI 视频生成平台，创建专业讲解视频',
    category: 'AI 视频',
    tags: ['视频生成', '讲解视频', '企业'],
    pricing: '付费',
    rating: 4.4,
    popularity: 30000,
    chinese: false,
    icon: '📹',
    color: 'green'
  },
  {
    id: '310',
    name: 'InVideo',
    url: 'https://invideo.io',
    description: 'AI 视频编辑和制作平台',
    category: 'AI 视频',
    tags: ['视频编辑', '模板', '在线'],
    pricing: '免费 + 付费',
    rating: 4.2,
    popularity: 40000,
    chinese: false,
    icon: '📺',
    color: 'purple'
  },

  // ============== AI 音频 (8 个) ==============
  {
    id: '401',
    name: 'ElevenLabs',
    url: 'https://elevenlabs.io',
    description: '最逼真的 AI 语音合成工具，支持多语言、情感表达',
    category: 'AI 音频',
    tags: ['语音合成', '多语言', '逼真'],
    pricing: '免费 + 付费',
    rating: 4.7,
    popularity: 60000,
    chinese: false,
    icon: '🔊',
    color: 'green'
  },
  {
    id: '402',
    name: 'Suno AI',
    url: 'https://suno.com',
    description: 'AI 音乐生成工具，根据文字描述创作完整歌曲',
    category: 'AI 音频',
    tags: ['音乐生成', '歌曲创作', 'AI 作曲'],
    pricing: '免费 + 付费',
    rating: 4.6,
    popularity: 55000,
    chinese: false,
    icon: '🎵',
    color: 'purple'
  },
  {
    id: '403',
    name: '讯飞配音',
    url: 'https://peiyin.xunfei.cn',
    description: '科大讯飞推出的 AI 配音服务，支持多种音色和场景',
    category: 'AI 音频',
    tags: ['配音', '国产', '多音色'],
    pricing: '免费 + 付费',
    rating: 4.5,
    popularity: 50000,
    chinese: true,
    icon: '🎙️',
    color: 'blue'
  },
  {
    id: '404',
    name: 'Adobe Podcast',
    url: 'https://podcast.adobe.com',
    description: 'Adobe 推出的 AI 播客工具，自动降噪、增强音质',
    category: 'AI 音频',
    tags: ['播客', '降噪', '音质增强'],
    pricing: '免费 + 付费',
    rating: 4.4,
    popularity: 35000,
    chinese: false,
    icon: '🎧',
    color: 'red'
  },
  {
    id: '405',
    name: 'Murf AI',
    url: 'https://murf.ai',
    description: 'AI 语音生成平台，适合企业视频配音',
    category: 'AI 音频',
    tags: ['语音生成', '企业', '配音'],
    pricing: '免费 + 付费',
    rating: 4.3,
    popularity: 25000,
    chinese: false,
    icon: '🎤',
    color: 'green'
  },
  {
    id: '406',
    name: 'PlayHT',
    url: 'https://play.ht',
    description: 'AI 语音生成 API，支持多种语言和音色',
    category: 'AI 音频',
    tags: ['语音 API', '多语言', '开发者'],
    pricing: '免费 + 付费',
    rating: 4.2,
    popularity: 20000,
    chinese: false,
    icon: '▶️',
    color: 'purple'
  },
  {
    id: '407',
    name: 'RVC',
    url: 'https://github.com/RVC-Project',
    description: '开源的 AI 变声工具，效果逼真',
    category: 'AI 音频',
    tags: ['变声', '开源', 'GitHub'],
    pricing: '免费',
    rating: 4.5,
    popularity: 45000,
    chinese: true,
    icon: '🔄',
    color: 'red'
  },
  {
    id: '408',
    name: '网易云音乐 AI',
    url: 'https://music.163.com',
    description: '网易云音乐的 AI 音乐推荐和创作功能',
    category: 'AI 音频',
    tags: ['音乐', '国产', '推荐'],
    pricing: '免费 + 付费',
    rating: 4.4,
    popularity: 80000,
    chinese: true,
    icon: '🎶',
    color: 'red'
  },

  // ============== 编程开发 (10 个) ==============
  {
    id: '501',
    name: 'GitHub Copilot',
    url: 'https://github.com/features/copilot',
    description: 'GitHub 和 OpenAI 合作的 AI 编程助手，自动补全代码',
    category: '编程开发',
    tags: ['代码补全', 'GitHub', '微软'],
    pricing: '付费',
    rating: 4.7,
    popularity: 85000,
    chinese: false,
    icon: '💻',
    color: 'gray'
  },
  {
    id: '502',
    name: 'Cursor',
    url: 'https://cursor.sh',
    description: 'AI 驱动的代码编辑器，内置 AI 对话和代码生成',
    category: '编程开发',
    tags: ['代码编辑器', 'AI 对话', '代码生成'],
    pricing: '免费 + 付费',
    rating: 4.8,
    popularity: 50000,
    chinese: false,
    icon: '🔮',
    color: 'blue'
  },
  {
    id: '503',
    name: 'Codeium',
    url: 'https://codeium.com',
    description: '免费的 AI 编程助手，支持多种 IDE 和编程语言',
    category: '编程开发',
    tags: ['代码补全', '免费', '多语言'],
    pricing: '免费',
    rating: 4.5,
    popularity: 40000,
    chinese: false,
    icon: '⚡',
    color: 'purple'
  },
  {
    id: '504',
    name: '通义灵码',
    url: 'https://tongyi.aliyun.com/lingma',
    description: '阿里云推出的 AI 编程助手，支持代码生成、解释、优化',
    category: '编程开发',
    tags: ['代码助手', '国产', '阿里系'],
    pricing: '免费',
    rating: 4.4,
    popularity: 35000,
    chinese: true,
    icon: '🔧',
    color: 'blue'
  },
  {
    id: '505',
    name: 'CodeWhisperer',
    url: 'https://aws.amazon.com/codewhisperer',
    description: '亚马逊推出的 AI 编程助手，集成 AWS 服务',
    category: '编程开发',
    tags: ['代码助手', 'AWS', '安全'],
    pricing: '免费 + 付费',
    rating: 4.3,
    popularity: 30000,
    chinese: false,
    icon: '📡',
    color: 'orange'
  },
  {
    id: '506',
    name: 'Tabnine',
    url: 'https://www.tabnine.com',
    description: 'AI 代码补全工具，支持本地部署',
    category: '编程开发',
    tags: ['代码补全', '本地部署', '隐私'],
    pricing: '免费 + 付费',
    rating: 4.4,
    popularity: 35000,
    chinese: false,
    icon: '📑',
    color: 'blue'
  },
  {
    id: '507',
    name: 'Replit AI',
    url: 'https://replit.com',
    description: '在线 IDE 的 AI 编程助手',
    category: '编程开发',
    tags: ['在线 IDE', '代码助手', '协作'],
    pricing: '免费 + 付费',
    rating: 4.3,
    popularity: 40000,
    chinese: false,
    icon: '🔁',
    color: 'orange'
  },
  {
    id: '508',
    name: 'CodeGeeX',
    url: 'https://codegeex.cn',
    description: '清华推出的 AI 编程助手，支持多种语言',
    category: '编程开发',
    tags: ['代码助手', '国产', '清华'],
    pricing: '免费',
    rating: 4.3,
    popularity: 25000,
    chinese: true,
    icon: '🇨🇳',
    color: 'red'
  },
  {
    id: '509',
    name: 'Bito AI',
    url: 'https://bito.ai',
    description: 'AI 编程助手，支持代码解释、测试生成',
    category: '编程开发',
    tags: ['代码助手', '测试生成', '解释'],
    pricing: '免费 + 付费',
    rating: 4.2,
    popularity: 20000,
    chinese: false,
    icon: '🔩',
    color: 'blue'
  },
  {
    id: '510',
    name: 'Blackbox AI',
    url: 'https://www.blackbox.ai',
    description: 'AI 编程助手，支持代码搜索和生成',
    category: '编程开发',
    tags: ['代码搜索', '代码生成', 'AI'],
    pricing: '免费 + 付费',
    rating: 4.1,
    popularity: 25000,
    chinese: false,
    icon: '📦',
    color: 'black'
  },

  // ============== 办公效率 (10 个) ==============
  {
    id: '601',
    name: 'Gamma',
    url: 'https://gamma.app',
    description: 'AI 演示文稿生成工具，快速创建精美的 PPT',
    category: '办公效率',
    tags: ['PPT 生成', '演示文稿', '设计'],
    pricing: '免费 + 付费',
    rating: 4.6,
    popularity: 55000,
    chinese: false,
    icon: '📊',
    color: 'white'
  },
  {
    id: '602',
    name: 'Tome',
    url: 'https://tome.app',
    description: 'AI 故事叙述和演示工具，创建交互式演示',
    category: '办公效率',
    tags: ['演示文稿', '故事叙述', '交互式'],
    pricing: '免费 + 付费',
    rating: 4.4,
    popularity: 40000,
    chinese: false,
    icon: '📖',
    color: 'pink'
  },
  {
    id: '603',
    name: 'Beautiful.ai',
    url: 'https://www.beautiful.ai',
    description: 'AI 驱动的 PPT 设计工具，自动调整布局和样式',
    category: '办公效率',
    tags: ['PPT 设计', '自动布局', '专业'],
    pricing: '付费',
    rating: 4.3,
    popularity: 35000,
    chinese: false,
    icon: '🎯',
    color: 'blue'
  },
  {
    id: '604',
    name: 'WPS AI',
    url: 'https://www.wps.cn/ai',
    description: '金山办公推出的 AI 助手，集成在 WPS Office 中',
    category: '办公效率',
    tags: ['Office', '国产', '文档处理'],
    pricing: '免费 + 付费',
    rating: 4.4,
    popularity: 60000,
    chinese: true,
    icon: '📄',
    color: 'red'
  },
  {
    id: '605',
    name: 'Microsoft 365 Copilot',
    url: 'https://www.microsoft.com/microsoft-365/copilot',
    description: '微软推出的 AI 办公助手，集成在 Office 全家桶',
    category: '办公效率',
    tags: ['Office', '微软', '全家桶'],
    pricing: '付费',
    rating: 4.5,
    popularity: 70000,
    chinese: true,
    icon: '📘',
    color: 'blue'
  },
  {
    id: '606',
    name: 'Canva AI',
    url: 'https://www.canva.com/ai',
    description: 'Canva 的 AI 设计功能，支持魔法编辑、背景移除等',
    category: '办公效率',
    tags: ['设计', 'AI 编辑', '在线'],
    pricing: '免费 + 付费',
    rating: 4.5,
    popularity: 80000,
    chinese: true,
    icon: '🎨',
    color: 'purple'
  },
  {
    id: '607',
    name: 'MindShow',
    url: 'https://www.mindshow.fun',
    description: 'AI 思维导图和 PPT 生成工具',
    category: '办公效率',
    tags: ['思维导图', 'PPT', '国产'],
    pricing: '免费 + 付费',
    rating: 4.3,
    popularity: 30000,
    chinese: true,
    icon: '🧠',
    color: 'orange'
  },
  {
    id: '608',
    name: 'ChatBA',
    url: 'https://www.chatba.com',
    description: 'AI 生成 PPT 和演示文稿',
    category: '办公效率',
    tags: ['PPT 生成', '演示', 'AI'],
    pricing: '免费 + 付费',
    rating: 4.1,
    popularity: 20000,
    chinese: false,
    icon: '📽️',
    color: 'blue'
  },
  {
    id: '609',
    name: 'Slack AI',
    url: 'https://slack.com/features/ai',
    description: 'Slack 内置的 AI 助手，帮助总结对话、提取要点',
    category: '办公效率',
    tags: ['团队协作', '总结', '沟通'],
    pricing: '付费',
    rating: 4.2,
    popularity: 50000,
    chinese: false,
    icon: '💬',
    color: 'purple'
  },
  {
    id: '610',
    name: 'Otter.ai',
    url: 'https://otter.ai',
    description: 'AI 会议记录工具，自动转录和总结',
    category: '办公效率',
    tags: ['会议记录', '转录', '总结'],
    pricing: '免费 + 付费',
    rating: 4.4,
    popularity: 45000,
    chinese: false,
    icon: '🦦',
    color: 'blue'
  },

  // ============== 搜索研究 (6 个) ==============
  {
    id: '701',
    name: 'Perplexity AI',
    url: 'https://www.perplexity.ai',
    description: 'AI 搜索引擎，提供准确答案并附带引用来源',
    category: '搜索研究',
    tags: ['搜索', '问答', '引用'],
    pricing: '免费 + 付费',
    rating: 4.7,
    popularity: 65000,
    chinese: false,
    icon: '🔍',
    color: 'green'
  },
  {
    id: '702',
    name: 'Consensus',
    url: 'https://consensus.app',
    description: 'AI 研究助手，搜索和总结科学论文',
    category: '搜索研究',
    tags: ['学术研究', '论文', '科学'],
    pricing: '免费 + 付费',
    rating: 4.5,
    popularity: 30000,
    chinese: false,
    icon: '📚',
    color: 'blue'
  },
  {
    id: '703',
    name: 'Elicit',
    url: 'https://elicit.org',
    description: 'AI 研究助手，帮助查找和分析研究论文',
    category: '搜索研究',
    tags: ['学术研究', '论文分析', '文献'],
    pricing: '免费 + 付费',
    rating: 4.4,
    popularity: 25000,
    chinese: false,
    icon: '🔬',
    color: 'purple'
  },
  {
    id: '704',
    name: '天工 AI',
    url: 'https://tiangong.kunlun.com',
    description: '昆仑万维推出的 AI 搜索助手，支持多轮对话',
    category: '搜索研究',
    tags: ['搜索', '国产', '对话'],
    pricing: '免费',
    rating: 4.3,
    popularity: 35000,
    chinese: true,
    icon: '🌤️',
    color: 'blue'
  },
  {
    id: '705',
    name: 'You.com',
    url: 'https://you.com',
    description: 'AI 搜索引擎，注重隐私和个性化',
    category: '搜索研究',
    tags: ['搜索', '隐私', '个性化'],
    pricing: '免费 + 付费',
    rating: 4.3,
    popularity: 40000,
    chinese: false,
    icon: '🔎',
    color: 'blue'
  },
  {
    id: '706',
    name: 'Phind',
    url: 'https://www.phind.com',
    description: '面向开发者的 AI 搜索引擎',
    category: '搜索研究',
    tags: ['搜索', '开发者', '技术'],
    pricing: '免费 + 付费',
    rating: 4.6,
    popularity: 35000,
    chinese: false,
    icon: '🔧',
    color: 'green'
  },

  // ============== 教育学习 (6 个) ==============
  {
    id: '801',
    name: 'Khanmigo',
    url: 'https://www.khanacademy.org/khan-labs',
    description: '可汗学院推出的 AI 辅导老师，个性化教学',
    category: '教育学习',
    tags: ['教育', '辅导', '个性化'],
    pricing: '付费',
    rating: 4.6,
    popularity: 40000,
    chinese: false,
    icon: '🎓',
    color: 'green'
  },
  {
    id: '802',
    name: 'Quizlet AI',
    url: 'https://quizlet.com/ai',
    description: 'Quizlet 推出的 AI 学习工具，自动生成练习题',
    category: '教育学习',
    tags: ['学习', '练习题', '记忆'],
    pricing: '免费 + 付费',
    rating: 4.4,
    popularity: 50000,
    chinese: true,
    icon: '📝',
    color: 'blue'
  },
  {
    id: '803',
    name: 'Duolingo Max',
    url: 'https://www.duolingo.com',
    description: '多邻国推出的 AI 语言学习功能，角色扮演对话',
    category: '教育学习',
    tags: ['语言学习', '对话', '英语'],
    pricing: '付费',
    rating: 4.5,
    popularity: 55000,
    chinese: true,
    icon: '🦉',
    color: 'green'
  },
  {
    id: '804',
    name: 'Wolfram Alpha',
    url: 'https://www.wolframalpha.com',
    description: '计算知识引擎，解答数学和科学问题',
    category: '教育学习',
    tags: ['数学', '科学', '计算'],
    pricing: '免费 + 付费',
    rating: 4.6,
    popularity: 60000,
    chinese: false,
    icon: '🔢',
    color: 'orange'
  },
  {
    id: '805',
    name: 'Photomath',
    url: 'https://photomath.com',
    description: '拍照解题的数学学习工具',
    category: '教育学习',
    tags: ['数学', '拍照解题', '学习'],
    pricing: '免费 + 付费',
    rating: 4.5,
    popularity: 70000,
    chinese: true,
    icon: '📸',
    color: 'blue'
  },
  {
    id: '806',
    name: '作业帮 AI',
    url: 'https://www.zuoyebang.com',
    description: '作业帮推出的 AI 学习辅导工具',
    category: '教育学习',
    tags: ['学习辅导', '国产', '拍照解题'],
    pricing: '免费 + 付费',
    rating: 4.3,
    popularity: 80000,
    chinese: true,
    icon: '📚',
    color: 'blue'
  },

  // ============== 商业营销 (5 个) ==============
  {
    id: '901',
    name: 'Jasper',
    url: 'https://www.jasper.ai',
    description: '企业级 AI 内容创作平台，适合营销团队',
    category: '商业营销',
    tags: ['营销', '企业级', '内容创作'],
    pricing: '付费',
    rating: 4.4,
    popularity: 45000,
    chinese: false,
    icon: '📈',
    color: 'pink'
  },
  {
    id: '902',
    name: 'AdCreative.ai',
    url: 'https://www.adcreative.ai',
    description: 'AI 广告创意生成工具，快速创建高转化率广告',
    category: '商业营销',
    tags: ['广告', '创意', '转化率'],
    pricing: '付费',
    rating: 4.3,
    popularity: 30000,
    chinese: false,
    icon: '📢',
    color: 'orange'
  },
  {
    id: '903',
    name: 'Journey AI',
    url: 'https://www.journey.ai',
    description: 'AI 营销自动化平台',
    category: '商业营销',
    tags: ['营销自动化', '企业', 'CRM'],
    pricing: '付费',
    rating: 4.2,
    popularity: 20000,
    chinese: false,
    icon: '🗺️',
    color: 'blue'
  },
  {
    id: '904',
    name: 'Predis.ai',
    url: 'https://predis.ai',
    description: 'AI 社交媒体内容生成工具',
    category: '商业营销',
    tags: ['社交媒体', '内容生成', '营销'],
    pricing: '免费 + 付费',
    rating: 4.1,
    popularity: 25000,
    chinese: false,
    icon: '📱',
    color: 'purple'
  },
  {
    id: '905',
    name: 'Ocoya',
    url: 'https://ocoya.com',
    description: 'AI 社交媒体管理和内容生成',
    category: '商业营销',
    tags: ['社交媒体', '管理', '调度'],
    pricing: '免费 + 付费',
    rating: 4.2,
    popularity: 22000,
    chinese: false,
    icon: '🌐',
    color: 'pink'
  },

  // ============== 数据处理 (5 个) ==============
  {
    id: '1001',
    name: 'Julius AI',
    url: 'https://julius.ai',
    description: 'AI 数据分析师，自然语言进行数据分析',
    category: '数据处理',
    tags: ['数据分析', '可视化', '自然语言'],
    pricing: '免费 + 付费',
    rating: 4.5,
    popularity: 25000,
    chinese: false,
    icon: '📊',
    color: 'blue'
  },
  {
    id: '1002',
    name: 'Akkio',
    url: 'https://www.akkio.com',
    description: 'AI 预测分析平台，无需编程即可创建预测模型',
    category: '数据处理',
    tags: ['预测分析', '无代码', '机器学习'],
    pricing: '付费',
    rating: 4.3,
    popularity: 20000,
    chinese: false,
    icon: '🔮',
    color: 'purple'
  },
  {
    id: '1003',
    name: 'MonkeyLearn',
    url: 'https://monkeylearn.com',
    description: 'AI 文本分析平台，情感分析、分类',
    category: '数据处理',
    tags: ['文本分析', '情感分析', 'NLP'],
    pricing: '免费 + 付费',
    rating: 4.2,
    popularity: 18000,
    chinese: false,
    icon: '🐒',
    color: 'orange'
  },
  {
    id: '1004',
    name: 'Obviously AI',
    url: 'https://www.obviously.ai',
    description: 'AI 预测平台，快速创建预测模型',
    category: '数据处理',
    tags: ['预测', '机器学习', '快速'],
    pricing: '免费 + 付费',
    rating: 4.1,
    popularity: 15000,
    chinese: false,
    icon: '💡',
    color: 'yellow'
  },
  {
    id: '1005',
    name: 'Tableau AI',
    url: 'https://www.tableau.com/products/ai',
    description: 'Tableau 的 AI 数据分析功能',
    category: '数据处理',
    tags: ['数据分析', '可视化', 'BI'],
    pricing: '付费',
    rating: 4.4,
    popularity: 40000,
    chinese: false,
    icon: '📈',
    color: 'blue'
  },

  // ============== 电商工具 (5 个) ==============
  {
    id: '1101',
    name: 'Shopify AI',
    url: 'https://www.shopify.com/ai',
    description: 'Shopify 的 AI 电商工具，帮助商品描述、客服',
    category: '电商工具',
    tags: ['电商', 'Shopify', '商品描述'],
    pricing: '付费',
    rating: 4.4,
    popularity: 50000,
    chinese: true,
    icon: '🛍️',
    color: 'green'
  },
  {
    id: '1102',
    name: 'PhotoRoom',
    url: 'https://www.photoroom.com',
    description: 'AI 商品图处理工具，自动抠图、换背景',
    category: '电商工具',
    tags: ['商品图', '抠图', '背景'],
    pricing: '免费 + 付费',
    rating: 4.5,
    popularity: 45000,
    chinese: false,
    icon: '📷',
    color: 'purple'
  },
  {
    id: '1103',
    name: 'Flair AI',
    url: 'https://flair.ai',
    description: 'AI 商品摄影工具，生成专业产品图',
    category: '电商工具',
    tags: ['商品摄影', '产品图', '生成'],
    pricing: '免费 + 付费',
    rating: 4.3,
    popularity: 25000,
    chinese: false,
    icon: '✨',
    color: 'pink'
  },
  {
    id: '1104',
    name: 'Peppertype.ai',
    url: 'https://www.peppertype.ai',
    description: 'AI 电商内容生成工具',
    category: '电商工具',
    tags: ['电商', '内容生成', '产品描述'],
    pricing: '免费 + 付费',
    rating: 4.1,
    popularity: 18000,
    chinese: false,
    icon: '📝',
    color: 'orange'
  },
  {
    id: '1105',
    name: 'Zyro AI',
    url: 'https://zyro.com/ai',
    description: 'AI 建站和内容生成工具',
    category: '电商工具',
    tags: ['建站', '电商', '内容生成'],
    pricing: '付费',
    rating: 4.2,
    popularity: 22000,
    chinese: false,
    icon: '🌐',
    color: 'blue'
  },

  // ============== 人力资源 (4 个) ==============
  {
    id: '1201',
    name: 'Resume.io',
    url: 'https://resume.io',
    description: 'AI 简历制作工具，智能生成简历',
    category: '人力资源',
    tags: ['简历', '求职', '生成'],
    pricing: '免费 + 付费',
    rating: 4.3,
    popularity: 40000,
    chinese: false,
    icon: '📄',
    color: 'blue'
  },
  {
    id: '1202',
    name: 'Kickresume',
    url: 'https://www.kickresume.com',
    description: 'AI 简历和求职信生成器',
    category: '人力资源',
    tags: ['简历', '求职信', 'AI 生成'],
    pricing: '免费 + 付费',
    rating: 4.2,
    popularity: 30000,
    chinese: false,
    icon: '📋',
    color: 'orange'
  },
  {
    id: '1203',
    name: 'HireVue',
    url: 'https://www.hirevue.com',
    description: 'AI 视频面试平台',
    category: '人力资源',
    tags: ['视频面试', '招聘', '评估'],
    pricing: '付费',
    rating: 4.1,
    popularity: 25000,
    chinese: false,
    icon: '📹',
    color: 'blue'
  },
  {
    id: '1204',
    name: 'Pymetrics',
    url: 'https://pymetrics.com',
    description: 'AI 人才评估平台',
    category: '人力资源',
    tags: ['人才评估', '招聘', '测试'],
    pricing: '付费',
    rating: 4.0,
    popularity: 18000,
    chinese: false,
    icon: '🧠',
    color: 'purple'
  },

  // ============== 法律科技 (3 个) ==============
  {
    id: '1301',
    name: 'Harvey AI',
    url: 'https://harvey.ai',
    description: 'AI 法律助手，帮助法律研究和文书写作',
    category: '法律科技',
    tags: ['法律', '研究', '文书'],
    pricing: '付费',
    rating: 4.5,
    popularity: 20000,
    chinese: false,
    icon: '⚖️',
    color: 'blue'
  },
  {
    id: '1302',
    name: 'Casetext',
    url: 'https://casetext.com',
    description: 'AI 法律研究平台',
    category: '法律科技',
    tags: ['法律研究', '案例', 'AI'],
    pricing: '付费',
    rating: 4.3,
    popularity: 15000,
    chinese: false,
    icon: '📚',
    color: 'gray'
  },
  {
    id: '1303',
    name: 'LawGeex',
    url: 'https://www.lawgeex.com',
    description: 'AI 合同审查平台',
    category: '法律科技',
    tags: ['合同审查', '法律', '自动化'],
    pricing: '付费',
    rating: 4.2,
    popularity: 12000,
    chinese: false,
    icon: '📑',
    color: 'green'
  },

  // ============== 医疗健康 (4 个) ==============
  {
    id: '1401',
    name: 'Ada Health',
    url: 'https://ada.com',
    description: 'AI 健康评估工具',
    category: '医疗健康',
    tags: ['健康评估', '医疗', '诊断'],
    pricing: '免费',
    rating: 4.4,
    popularity: 50000,
    chinese: false,
    icon: '🏥',
    color: 'blue'
  },
  {
    id: '1402',
    name: 'Babylon Health',
    url: 'https://www.babylonhealth.com',
    description: 'AI 医疗咨询平台',
    category: '医疗健康',
    tags: ['医疗咨询', '在线问诊', 'AI'],
    pricing: '付费',
    rating: 4.2,
    popularity: 35000,
    chinese: false,
    icon: '💊',
    color: 'blue'
  },
  {
    id: '1403',
    name: 'Buoy Health',
    url: 'https://www.buoyhealth.com',
    description: 'AI 症状检查工具',
    category: '医疗健康',
    tags: ['症状检查', '健康', 'AI'],
    pricing: '免费',
    rating: 4.3,
    popularity: 30000,
    chinese: false,
    icon: '🌊',
    color: 'blue'
  },
  {
    id: '1404',
    name: 'Insilico Medicine',
    url: 'https://insilico.com',
    description: 'AI 药物研发平台',
    category: '医疗健康',
    tags: ['药物研发', 'AI', '生物科技'],
    pricing: '付费',
    rating: 4.5,
    popularity: 15000,
    chinese: false,
    icon: '🧬',
    color: 'purple'
  },

  // ============== 游戏娱乐 (4 个) ==============
  {
    id: '1501',
    name: 'Inworld AI',
    url: 'https://inworld.ai',
    description: 'AI 游戏 NPC 生成平台',
    category: '游戏娱乐',
    tags: ['游戏', 'NPC', 'AI 角色'],
    pricing: '免费 + 付费',
    rating: 4.4,
    popularity: 25000,
    chinese: false,
    icon: '🎮',
    color: 'purple'
  },
  {
    id: '1502',
    name: 'Modl.ai',
    url: 'https://modl.ai',
    description: 'AI 游戏测试和开发工具',
    category: '游戏娱乐',
    tags: ['游戏开发', '测试', 'AI'],
    pricing: '付费',
    rating: 4.2,
    popularity: 15000,
    chinese: false,
    icon: '🕹️',
    color: 'blue'
  },
  {
    id: '1503',
    name: 'Promethean AI',
    url: 'https://www.prometheanai.com',
    description: 'AI 游戏场景生成工具',
    category: '游戏娱乐',
    tags: ['游戏场景', '3D', '生成'],
    pricing: '付费',
    rating: 4.3,
    popularity: 18000,
    chinese: false,
    icon: '🏰',
    color: 'orange'
  },
  {
    id: '1504',
    name: 'Ludo AI',
    url: 'https://ludo.ai',
    description: 'AI 游戏研究和灵感工具',
    category: '游戏娱乐',
    tags: ['游戏研究', '灵感', '分析'],
    pricing: '付费',
    rating: 4.1,
    popularity: 12000,
    chinese: false,
    icon: '🎲',
    color: 'purple'
  }
]

export const categories = [
  { id: 'all', name: '全部', icon: '🌟' },
  { id: '对话助手', name: '对话助手', icon: '🤖' },
  { id: 'AI 写作', name: 'AI 写作', icon: '✍️' },
  { id: 'AI 绘画', name: 'AI 绘画', icon: '🎨' },
  { id: 'AI 视频', name: 'AI 视频', icon: '🎬' },
  { id: 'AI 音频', name: 'AI 音频', icon: '🔊' },
  { id: '编程开发', name: '编程开发', icon: '💻' },
  { id: '办公效率', name: '办公效率', icon: '📊' },
  { id: '搜索研究', name: '搜索研究', icon: '🔍' },
  { id: '教育学习', name: '教育学习', icon: '🎓' },
  { id: '商业营销', name: '商业营销', icon: '📈' },
  { id: '数据处理', name: '数据处理', icon: '📊' },
  { id: '电商工具', name: '电商工具', icon: '🛍️' },
  { id: '人力资源', name: '人力资源', icon: '👥' },
  { id: '法律科技', name: '法律科技', icon: '⚖️' },
  { id: '医疗健康', name: '医疗健康', icon: '🏥' },
  { id: '游戏娱乐', name: '游戏娱乐', icon: '🎮' }
]
